# 2.3数组的索引切片 

In [1]:
import numpy as np
#先行后列
score = np.array(
[[80, 89, 86, 67, 79],
[78, 97, 89, 67, 81],
[90, 94, 78, 67, 74],
[91, 91, 90, 67, 69],
[76, 87, 75, 67, 86],
[70, 79, 84, 67, 84],
[94, 92, 93, 67, 64],
[86, 85, 83, 67, 80]])

score 

array([[80, 89, 86, 67, 79],
       [78, 97, 89, 67, 81],
       [90, 94, 78, 67, 74],
       [91, 91, 90, 67, 69],
       [76, 87, 75, 67, 86],
       [70, 79, 84, 67, 84],
       [94, 92, 93, 67, 64],
       [86, 85, 83, 67, 80]])

In [3]:
a = score[0:2]
a



array([[80, 89, 86, 67, 79],
       [78, 97, 89, 67, 81]])

In [9]:
score

array([[80, 89, 86, 67, 79],
       [78, 97, 89, 67, 81],
       [90, 94, 78, 67, 74],
       [91, 91, 90, 67, 69],
       [76, 87, 75, 67, 86],
       [70, 79, 84, 67, 84],
       [94, 92, 93, 67, 64],
       [86, 85, 83, 67, 80]])

In [11]:
b =score[0:6:2]
b

array([[80, 89, 86, 67, 79],
       [90, 94, 78, 67, 74],
       [76, 87, 75, 67, 86]])

In [12]:
stock_change = np.random.normal(0, 1, (4, 5))
stock_change

array([[-0.98081713, -0.41649039,  0.12724711,  0.21905318,  1.418156  ],
       [ 0.31624014,  0.4015088 , -1.73860881,  0.75655918,  0.34566011],
       [-1.40251268,  0.41817437,  0.2442605 , -1.08838745, -0.85110937],
       [-0.23862274, -1.65002846,  0.22650987,  0.286483  ,  0.99613861]])

In [14]:
a = stock_change[0,0:3]
a

array([-0.98081713, -0.41649039,  0.12724711])

In [16]:
b = stock_change[3,0:2]
b

array([-0.23862274, -1.65002846])

In [17]:
ge = np.random.normal(0, 1, (4, 5,3))
ge

array([[[-1.41904688,  1.17349886, -0.17098666],
        [-0.38896428,  0.45614344,  0.9512716 ],
        [-1.34291433, -1.79733163,  0.3033057 ],
        [-1.84281515, -0.1052271 ,  1.4606005 ],
        [ 0.91517216,  0.17975975, -0.08613205]],

       [[-0.51274336,  0.79187659, -0.77991749],
        [ 0.5113401 ,  1.76880218,  0.49525885],
        [ 1.10478006, -0.33067071,  0.95685817],
        [-1.87528788,  1.70150549, -0.12417153],
        [-1.79659099, -0.5948463 , -0.07552007]],

       [[-0.60298072,  0.02487739, -2.64140598],
        [-1.00495349,  0.33756945, -0.25725355],
        [ 0.02804117,  0.50730936,  0.0212526 ],
        [ 0.37890175,  1.88820745, -1.0726292 ],
        [-0.24722333,  0.90799435,  0.34825169]],

       [[ 0.63456941, -0.55639469, -2.23040386],
        [ 0.71736555,  0.80988515,  0.97672718],
        [ 0.19888868, -0.55295678, -1.10624983],
        [ 0.63354489, -0.5859117 , -0.88180387],
        [-0.12768457,  0.80643835, -0.33125413]]])

In [18]:
c = ge[2,2,0]
c

0.028041168907289304

# 3.形状修改

In [21]:
#ndarray.reshape(shape,order)
ge.reshape([3,4,5])
ge

array([[[-1.41904688,  1.17349886, -0.17098666],
        [-0.38896428,  0.45614344,  0.9512716 ],
        [-1.34291433, -1.79733163,  0.3033057 ],
        [-1.84281515, -0.1052271 ,  1.4606005 ],
        [ 0.91517216,  0.17975975, -0.08613205]],

       [[-0.51274336,  0.79187659, -0.77991749],
        [ 0.5113401 ,  1.76880218,  0.49525885],
        [ 1.10478006, -0.33067071,  0.95685817],
        [-1.87528788,  1.70150549, -0.12417153],
        [-1.79659099, -0.5948463 , -0.07552007]],

       [[-0.60298072,  0.02487739, -2.64140598],
        [-1.00495349,  0.33756945, -0.25725355],
        [ 0.02804117,  0.50730936,  0.0212526 ],
        [ 0.37890175,  1.88820745, -1.0726292 ],
        [-0.24722333,  0.90799435,  0.34825169]],

       [[ 0.63456941, -0.55639469, -2.23040386],
        [ 0.71736555,  0.80988515,  0.97672718],
        [ 0.19888868, -0.55295678, -1.10624983],
        [ 0.63354489, -0.5859117 , -0.88180387],
        [-0.12768457,  0.80643835, -0.33125413]]])

In [26]:
ge.reshape([5,3,4])
o = ge
o

array([[[-1.41904688,  1.17349886, -0.17098666],
        [-0.38896428,  0.45614344,  0.9512716 ],
        [-1.34291433, -1.79733163,  0.3033057 ],
        [-1.84281515, -0.1052271 ,  1.4606005 ],
        [ 0.91517216,  0.17975975, -0.08613205]],

       [[-0.51274336,  0.79187659, -0.77991749],
        [ 0.5113401 ,  1.76880218,  0.49525885],
        [ 1.10478006, -0.33067071,  0.95685817],
        [-1.87528788,  1.70150549, -0.12417153],
        [-1.79659099, -0.5948463 , -0.07552007]],

       [[-0.60298072,  0.02487739, -2.64140598],
        [-1.00495349,  0.33756945, -0.25725355],
        [ 0.02804117,  0.50730936,  0.0212526 ],
        [ 0.37890175,  1.88820745, -1.0726292 ],
        [-0.24722333,  0.90799435,  0.34825169]],

       [[ 0.63456941, -0.55639469, -2.23040386],
        [ 0.71736555,  0.80988515,  0.97672718],
        [ 0.19888868, -0.55295678, -1.10624983],
        [ 0.63354489, -0.5859117 , -0.88180387],
        [-0.12768457,  0.80643835, -0.33125413]]])

In [25]:
ge.reshape([-1,12])
ge

array([[[-1.41904688,  1.17349886, -0.17098666],
        [-0.38896428,  0.45614344,  0.9512716 ],
        [-1.34291433, -1.79733163,  0.3033057 ],
        [-1.84281515, -0.1052271 ,  1.4606005 ],
        [ 0.91517216,  0.17975975, -0.08613205]],

       [[-0.51274336,  0.79187659, -0.77991749],
        [ 0.5113401 ,  1.76880218,  0.49525885],
        [ 1.10478006, -0.33067071,  0.95685817],
        [-1.87528788,  1.70150549, -0.12417153],
        [-1.79659099, -0.5948463 , -0.07552007]],

       [[-0.60298072,  0.02487739, -2.64140598],
        [-1.00495349,  0.33756945, -0.25725355],
        [ 0.02804117,  0.50730936,  0.0212526 ],
        [ 0.37890175,  1.88820745, -1.0726292 ],
        [-0.24722333,  0.90799435,  0.34825169]],

       [[ 0.63456941, -0.55639469, -2.23040386],
        [ 0.71736555,  0.80988515,  0.97672718],
        [ 0.19888868, -0.55295678, -1.10624983],
        [ 0.63354489, -0.5859117 , -0.88180387],
        [-0.12768457,  0.80643835, -0.33125413]]])

In [27]:
o.shape


(4, 5, 3)

In [32]:
o.resize([3,5,4])
o.shape

(3, 5, 4)

In [33]:
o.T
o.shape

(3, 5, 4)

In [34]:
o

array([[[-1.41904688,  1.17349886, -0.17098666, -0.38896428],
        [ 0.45614344,  0.9512716 , -1.34291433, -1.79733163],
        [ 0.3033057 , -1.84281515, -0.1052271 ,  1.4606005 ],
        [ 0.91517216,  0.17975975, -0.08613205, -0.51274336],
        [ 0.79187659, -0.77991749,  0.5113401 ,  1.76880218]],

       [[ 0.49525885,  1.10478006, -0.33067071,  0.95685817],
        [-1.87528788,  1.70150549, -0.12417153, -1.79659099],
        [-0.5948463 , -0.07552007, -0.60298072,  0.02487739],
        [-2.64140598, -1.00495349,  0.33756945, -0.25725355],
        [ 0.02804117,  0.50730936,  0.0212526 ,  0.37890175]],

       [[ 1.88820745, -1.0726292 , -0.24722333,  0.90799435],
        [ 0.34825169,  0.63456941, -0.55639469, -2.23040386],
        [ 0.71736555,  0.80988515,  0.97672718,  0.19888868],
        [-0.55295678, -1.10624983,  0.63354489, -0.5859117 ],
        [-0.88180387, -0.12768457,  0.80643835, -0.33125413]]])

In [35]:
o.shape

(3, 5, 4)

In [36]:
o.T.shape

(4, 5, 3)

# 4.类型修改

In [38]:
a = np.array([1,2,3,4],dtype=np.int32)
a

array([1, 2, 3, 4], dtype=int32)

In [44]:
b = a.astype(np.int64)
#原来的a的类型并没有修改，修改的是之后的返回值
b.dtype

dtype('int64')

In [45]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[12, 3, 34], [5, 6, 7]]])
arr.tostring()

b'\x01\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x00\x00\x00\x00\x04\x00\x00\x00\x00\x00\x00\x00\x05\x00\x00\x00\x00\x00\x00\x00\x06\x00\x00\x00\x00\x00\x00\x00\x0c\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x00\x00\x00\x00"\x00\x00\x00\x00\x00\x00\x00\x05\x00\x00\x00\x00\x00\x00\x00\x06\x00\x00\x00\x00\x00\x00\x00\x07\x00\x00\x00\x00\x00\x00\x00'

# 5.去重

In [46]:
ge 

array([[[-1.41904688,  1.17349886, -0.17098666, -0.38896428],
        [ 0.45614344,  0.9512716 , -1.34291433, -1.79733163],
        [ 0.3033057 , -1.84281515, -0.1052271 ,  1.4606005 ],
        [ 0.91517216,  0.17975975, -0.08613205, -0.51274336],
        [ 0.79187659, -0.77991749,  0.5113401 ,  1.76880218]],

       [[ 0.49525885,  1.10478006, -0.33067071,  0.95685817],
        [-1.87528788,  1.70150549, -0.12417153, -1.79659099],
        [-0.5948463 , -0.07552007, -0.60298072,  0.02487739],
        [-2.64140598, -1.00495349,  0.33756945, -0.25725355],
        [ 0.02804117,  0.50730936,  0.0212526 ,  0.37890175]],

       [[ 1.88820745, -1.0726292 , -0.24722333,  0.90799435],
        [ 0.34825169,  0.63456941, -0.55639469, -2.23040386],
        [ 0.71736555,  0.80988515,  0.97672718,  0.19888868],
        [-0.55295678, -1.10624983,  0.63354489, -0.5859117 ],
        [-0.88180387, -0.12768457,  0.80643835, -0.33125413]]])

In [49]:
temp = np.array([[1, 2, 3,3,3,4],[3, 4, 5, 1,1,6]])
np.unique(temp)


array([1, 2, 3, 4, 5, 6])