# 1.逻辑运算

In [2]:
import numpy as np
#随机生成10名同学的5门功课   
score = np.random.randint(40,100,(10,5))
score

array([[85, 94, 45, 52, 47],
       [76, 95, 43, 88, 45],
       [77, 87, 41, 75, 70],
       [60, 65, 95, 93, 91],
       [90, 44, 73, 74, 40],
       [97, 87, 71, 76, 40],
       [49, 43, 68, 78, 98],
       [40, 98, 49, 57, 53],
       [94, 65, 67, 77, 52],
       [67, 45, 84, 46, 84]])

In [3]:
#取出最后4名同学的成绩 
last_four = score[6:,0:5]
last_four

array([[49, 43, 68, 78, 98],
       [40, 98, 49, 57, 53],
       [94, 65, 67, 77, 52],
       [67, 45, 84, 46, 84]])

In [4]:
last_four > 60


array([[False, False,  True,  True,  True],
       [False,  True, False, False, False],
       [ True,  True,  True,  True, False],
       [ True, False,  True, False,  True]])

In [8]:
last_four[last_four>60]=1
last_four

array([[49, 43,  1,  1,  1],
       [40,  1, 49, 57, 53],
       [ 1,  1,  1,  1, 52],
       [ 1, 45,  1, 46,  1]])

In [9]:
#np.all np.any
last_four

array([[49, 43,  1,  1,  1],
       [40,  1, 49, 57, 53],
       [ 1,  1,  1,  1, 52],
       [ 1, 45,  1, 46,  1]])

In [12]:
 np.all(last_four[0:2, :] <60)

True

In [14]:
np.any(last_four[0:2,:]>60)

False

# 3.三元运算符 where 

In [17]:
import numpy as np 
score = np.random.randint(40,100,(10,5))
score

array([[61, 77, 55, 81, 63],
       [90, 63, 83, 51, 59],
       [57, 66, 48, 90, 90],
       [86, 93, 68, 64, 74],
       [40, 83, 64, 77, 71],
       [47, 87, 99, 55, 84],
       [75, 61, 60, 99, 85],
       [88, 69, 77, 42, 78],
       [82, 80, 46, 57, 64],
       [72, 49, 80, 59, 45]])

In [20]:
#np.where()
#判断前4名学生，前四门课程中成绩大于60置为1，小于置为0
stu_sc =score[0:4,0:4]
stu_sc

array([[61, 77, 55, 81],
       [90, 63, 83, 51],
       [57, 66, 48, 90],
       [86, 93, 68, 64]])

In [21]:
np.where(stu_sc>60,1,0)

array([[1, 1, 0, 1],
       [1, 1, 1, 0],
       [0, 1, 0, 1],
       [1, 1, 1, 1]])

In [22]:
#逻辑与 逻辑或
#logical_and   logical_or
np.where(np.logical_and(stu_sc>80,stu_sc<90),1,0)

array([[0, 0, 0, 1],
       [0, 0, 1, 0],
       [0, 0, 0, 0],
       [1, 0, 0, 0]])

In [23]:
np.where(np.logical_or(stu_sc>80,stu_sc<90),1,0)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

# 4.统计运算

In [28]:
temp = score[:4, 0:5]
print("前四名学生,各科成绩的最大分：{}".format(np.max(temp, axis=0)))

前四名学生,各科成绩的最大分：[90 93 83 90 90]


In [26]:
temp

array([[61, 77, 55, 81, 63],
       [90, 63, 83, 51, 59],
       [57, 66, 48, 90, 90],
       [86, 93, 68, 64, 74]])

In [29]:
print("前四名学生，各科成绩的最小分数：{}".format(np.min(temp,axis=0)))

前四名学生，各科成绩的最小分数：[57 63 48 51 59]


In [30]:
print("前四名学生,各科成绩波动情况：{}".format(np.std(temp, axis=0)))
print("前四名学生,各科成绩的平均分：{}".format(np.mean(temp, axis=0)))

前四名学生,各科成绩波动情况：[14.63728117 11.75531795 13.35102992 15.07481343 12.01041215]
前四名学生,各科成绩的平均分：[73.5  74.75 63.5  71.5  71.5 ]


In [31]:
print("前四名学生，各科成绩最高分对应的学生下标：{}".format(np.argmax(temp, axis=0)))

前四名学生，各科成绩最高分对应的学生下标：[1 3 1 2 2]


In [32]:
temp

array([[61, 77, 55, 81, 63],
       [90, 63, 83, 51, 59],
       [57, 66, 48, 90, 90],
       [86, 93, 68, 64, 74]])

In [34]:
#argmax 返回结果的目标索引
np.median(temp, axis=0)

array([73.5, 71.5, 61.5, 72.5, 68.5])

In [35]:
np.mean(temp, axis=0)

array([73.5 , 74.75, 63.5 , 71.5 , 71.5 ])

In [36]:
np.std(temp, axis=0)

array([14.63728117, 11.75531795, 13.35102992, 15.07481343, 12.01041215])

In [37]:
np.var(temp, axis=0)

array([214.25  , 138.1875, 178.25  , 227.25  , 144.25  ])

In [38]:
arr = np.array([[1, 2, 3, 2, 1, 4], [5, 6, 1, 2, 3, 1]])
a=arr + 1
b=arr / 2

a

array([[2, 3, 4, 3, 2, 5],
       [6, 7, 2, 3, 4, 2]])

In [39]:
b

array([[0.5, 1. , 1.5, 1. , 0.5, 2. ],
       [2.5, 3. , 0.5, 1. , 1.5, 0.5]])

In [40]:
c = [1, 2, 3, 4, 5]
c * 3#长度乘以3

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [41]:
arr1 = np.array([[0],[1],[2],[3]])
arr1.shape

(4, 1)

In [44]:
arr2 = np.array([1,2,3,5])
arr2.shape

(4,)

In [45]:
arr1+arr2

array([[1, 2, 3, 5],
       [2, 3, 4, 6],
       [3, 4, 5, 7],
       [4, 5, 6, 8]])

In [59]:
import numpy as np
q = np.array([[1,2,3,4],[1,2,3,4]])
w = np.array([[1,2,3,4],[1,2,3,4]])
q.shape

(2, 4)

In [60]:
w.shape

(2, 4)

In [61]:
w+q

array([[2, 4, 6, 8],
       [2, 4, 6, 8]])

In [62]:
c= np.array([1,2,3,4])
c.shape

(4,)

In [63]:
w+q

array([[2, 4, 6, 8],
       [2, 4, 6, 8]])

In [64]:
q+c

array([[2, 4, 6, 8],
       [2, 4, 6, 8]])

In [65]:
q+c+w

array([[ 3,  6,  9, 12],
       [ 3,  6,  9, 12]])

In [66]:
ar1 = np.array([[1, 2, 3, 2, 1, 4], [5, 6, 1, 2, 3, 1]])
ar2 = np.array([[1], [3]])
ar1.shape

(2, 6)

In [67]:
ar2.shape

(2, 1)

In [68]:
ar2+ar1

array([[2, 3, 4, 3, 2, 5],
       [8, 9, 4, 5, 6, 4]])

In [69]:
ar1.shape

(2, 6)

In [70]:
ar3 = np.random.randint(1,10,(6,2))
ar3

array([[1, 4],
       [2, 9],
       [2, 4],
       [5, 6],
       [7, 1],
       [2, 7]])

In [71]:
np.matmul(ar1,ar3)

array([[ 36,  75],
       [ 52, 100]])

In [74]:
ll=4
# np.matmul(ar1,ll)
np.dot(ar1,ll)

array([[ 4,  8, 12,  8,  4, 16],
       [20, 24,  4,  8, 12,  4]])